server:
  port: 8081

spring:
  redis:
    host: localhost
    port: 6379

elasticsearch:
  host: search-crpyto-crunch-elasticsearch-y2o5bnrlo2pejnym25smqkflge.ap-northeast-2.es.amazonaws.com
  scheme: https
  port: 443
  username: admin
  password: ENC(seqL1L2p+jYtdboE4Brzjddu1ro0WqJ6mehHGci2TdY=)