server:
  port: 8081

spring:
  redis:
    host: localhost
    port: 6379

elasticsearch:
  host: search-crpyto-crunch-elasticsearch-y2o5bnrlo2pejnym25smqkflge.ap-northeast-2.es.amazonaws.com
  scheme: https
  port: 443
  username: admin
  password: ENC(s7+wu2i1tp+FNQqSnLFn1fnfvAaNnUcdHlAHv2pv65Y=)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}